apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logging-service-rolebinding
  labels:
    app.kubernetes.io/name: logging-service
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-service-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
