---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "streamduplicity-manager"
  labels:
    app: streamduplicity
    test: "streamduplicity"
    type: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamduplicity
      test: "streamduplicity"
      type: manager
  template:
    metadata:
      labels:
        app: streamduplicity
        test: "streamduplicity"
        type: manager
    spec:
      containers:
        - name: "streamduplicity-manager"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 2020
          volumeMounts:
            - name: "streamduplicity-config"
              mountPath: /etc/config
            - name: test-storage
              mountPath: /data/config
              readOnly: false
          env:
            - name: PRAVEGA_CONTROLLER_URI
              value: "{{ .Values.stream.controller_uri }}"
            - name: API_HOST
              value: http://streamduplicity-manager:2020
          command: ["sh", "-c"]
          args:
           - cp /etc/config/..data/config.properties /data/config/config.properties; chmod 755 /data/config/config.properties; sed -i 's/{//g' /data/config/config.properties; sed -i 's/":"//g' /data/config/config.properties; sed -i 's/",//g' /data/config/config.properties; sed -i 's/"//g' /data/config/config.properties; cp /data/config/config.properties /app/conf/config.properties; chmod +x /app/lib/streamduplicity.jar; java -jar /app/lib/streamduplicity.jar
      volumes:
        - name: "streamduplicity-config"
          configMap:
            name: "streamduplicity-config"
            items:
            - key: "streamduplicity"
              path: config.properties
        - name: test-storage
          emptyDir: {}
