apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logging-service-role
  labels:
    app.kubernetes.io/name: logging-service
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - configmaps
  - services
  - secrets
  - events
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
